//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceLOCTP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participante", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Participante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long Id_Participante1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Rut_Participante1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_Participante1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_Patreno_Participante1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_Materno_Participante1Field;
        
        private System.DateTime Fecha_Nacimiento_Participante1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id_Participante1 {
            get {
                return this.Id_Participante1Field;
            }
            set {
                if ((this.Id_Participante1Field.Equals(value) != true)) {
                    this.Id_Participante1Field = value;
                    this.RaisePropertyChanged("Id_Participante1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rut_Participante1 {
            get {
                return this.Rut_Participante1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Rut_Participante1Field, value) != true)) {
                    this.Rut_Participante1Field = value;
                    this.RaisePropertyChanged("Rut_Participante1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre_Participante1 {
            get {
                return this.Nombre_Participante1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_Participante1Field, value) != true)) {
                    this.Nombre_Participante1Field = value;
                    this.RaisePropertyChanged("Nombre_Participante1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellido_Patreno_Participante1 {
            get {
                return this.Apellido_Patreno_Participante1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_Patreno_Participante1Field, value) != true)) {
                    this.Apellido_Patreno_Participante1Field = value;
                    this.RaisePropertyChanged("Apellido_Patreno_Participante1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Apellido_Materno_Participante1 {
            get {
                return this.Apellido_Materno_Participante1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_Materno_Participante1Field, value) != true)) {
                    this.Apellido_Materno_Participante1Field = value;
                    this.RaisePropertyChanged("Apellido_Materno_Participante1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Fecha_Nacimiento_Participante1 {
            get {
                return this.Fecha_Nacimiento_Participante1Field;
            }
            set {
                if ((this.Fecha_Nacimiento_Participante1Field.Equals(value) != true)) {
                    this.Fecha_Nacimiento_Participante1Field = value;
                    this.RaisePropertyChanged("Fecha_Nacimiento_Participante1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Torneo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Torneo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long Id_Torneo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_Torneo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_Torneo1Field;
        
        private System.DateTime Fecha_Torneo1Field;
        
        private long Cantidad_Participante1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id_Torneo1 {
            get {
                return this.Id_Torneo1Field;
            }
            set {
                if ((this.Id_Torneo1Field.Equals(value) != true)) {
                    this.Id_Torneo1Field = value;
                    this.RaisePropertyChanged("Id_Torneo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre_Torneo1 {
            get {
                return this.Nombre_Torneo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_Torneo1Field, value) != true)) {
                    this.Nombre_Torneo1Field = value;
                    this.RaisePropertyChanged("Nombre_Torneo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion_Torneo1 {
            get {
                return this.Descripcion_Torneo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_Torneo1Field, value) != true)) {
                    this.Descripcion_Torneo1Field = value;
                    this.RaisePropertyChanged("Descripcion_Torneo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Fecha_Torneo1 {
            get {
                return this.Fecha_Torneo1Field;
            }
            set {
                if ((this.Fecha_Torneo1Field.Equals(value) != true)) {
                    this.Fecha_Torneo1Field = value;
                    this.RaisePropertyChanged("Fecha_Torneo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long Cantidad_Participante1 {
            get {
                return this.Cantidad_Participante1Field;
            }
            set {
                if ((this.Cantidad_Participante1Field.Equals(value) != true)) {
                    this.Cantidad_Participante1Field = value;
                    this.RaisePropertyChanged("Cantidad_Participante1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLOCTP.WebServiceLOCTPSoap")]
    public interface WebServiceLOCTPSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento participante del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregarParticipanteTorneoService", ReplyAction="*")]
        CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceResponse agregarParticipanteTorneoService(CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregarParticipanteTorneoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceResponse> agregarParticipanteTorneoServiceAsync(CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarParticipanteTorneoServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarParticipanteTorneoService", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequestBody Body;
        
        public agregarParticipanteTorneoServiceRequest() {
        }
        
        public agregarParticipanteTorneoServiceRequest(CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class agregarParticipanteTorneoServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceLOCTP.Participante participante;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CapaGUI.ServiceLOCTP.Torneo torneo;
        
        public agregarParticipanteTorneoServiceRequestBody() {
        }
        
        public agregarParticipanteTorneoServiceRequestBody(CapaGUI.ServiceLOCTP.Participante participante, CapaGUI.ServiceLOCTP.Torneo torneo) {
            this.participante = participante;
            this.torneo = torneo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarParticipanteTorneoServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarParticipanteTorneoServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceResponseBody Body;
        
        public agregarParticipanteTorneoServiceResponse() {
        }
        
        public agregarParticipanteTorneoServiceResponse(CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class agregarParticipanteTorneoServiceResponseBody {
        
        public agregarParticipanteTorneoServiceResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLOCTPSoapChannel : CapaGUI.ServiceLOCTP.WebServiceLOCTPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLOCTPSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceLOCTP.WebServiceLOCTPSoap>, CapaGUI.ServiceLOCTP.WebServiceLOCTPSoap {
        
        public WebServiceLOCTPSoapClient() {
        }
        
        public WebServiceLOCTPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLOCTPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLOCTPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLOCTPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceResponse CapaGUI.ServiceLOCTP.WebServiceLOCTPSoap.agregarParticipanteTorneoService(CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequest request) {
            return base.Channel.agregarParticipanteTorneoService(request);
        }
        
        public void agregarParticipanteTorneoService(CapaGUI.ServiceLOCTP.Participante participante, CapaGUI.ServiceLOCTP.Torneo torneo) {
            CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequest inValue = new CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequest();
            inValue.Body = new CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequestBody();
            inValue.Body.participante = participante;
            inValue.Body.torneo = torneo;
            CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceResponse retVal = ((CapaGUI.ServiceLOCTP.WebServiceLOCTPSoap)(this)).agregarParticipanteTorneoService(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceResponse> CapaGUI.ServiceLOCTP.WebServiceLOCTPSoap.agregarParticipanteTorneoServiceAsync(CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequest request) {
            return base.Channel.agregarParticipanteTorneoServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceResponse> agregarParticipanteTorneoServiceAsync(CapaGUI.ServiceLOCTP.Participante participante, CapaGUI.ServiceLOCTP.Torneo torneo) {
            CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequest inValue = new CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequest();
            inValue.Body = new CapaGUI.ServiceLOCTP.agregarParticipanteTorneoServiceRequestBody();
            inValue.Body.participante = participante;
            inValue.Body.torneo = torneo;
            return ((CapaGUI.ServiceLOCTP.WebServiceLOCTPSoap)(this)).agregarParticipanteTorneoServiceAsync(inValue);
        }
    }
}
