//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceLOC {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLOC.WebServiceLOCSoap")]
    public interface WebServiceLOCSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregarTorneoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void agregarTorneoService(CapaGUI.ServiceLOC.Torneo torneo, CapaGUI.ServiceLOC.Tipo_Torneo tp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregarTorneoService", ReplyAction="*")]
        System.Threading.Tasks.Task agregarTorneoServiceAsync(CapaGUI.ServiceLOC.Torneo torneo, CapaGUI.ServiceLOC.Tipo_Torneo tp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarTorneoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listarTorneoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarTorneoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listarTorneoServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarTorneoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void modificarTorneoService(CapaGUI.ServiceLOC.Torneo torneo, CapaGUI.ServiceLOC.Tipo_Torneo tp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarTorneoService", ReplyAction="*")]
        System.Threading.Tasks.Task modificarTorneoServiceAsync(CapaGUI.ServiceLOC.Torneo torneo, CapaGUI.ServiceLOC.Tipo_Torneo tp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarTorneoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarTorneoService(CapaGUI.ServiceLOC.Tipo_Torneo TP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarTorneoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscarTorneoServiceAsync(CapaGUI.ServiceLOC.Tipo_Torneo TP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarTorneoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarTorneoService(CapaGUI.ServiceLOC.Torneo torneo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarTorneoService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarTorneoServiceAsync(CapaGUI.ServiceLOC.Torneo torneo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdTorneo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscarIdTorneo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdTorneo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscarIdTorneoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerDatosTorneoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceLOC.Torneo TraerDatosTorneoService(CapaGUI.ServiceLOC.Torneo torneo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerDatosTorneoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceLOC.Torneo> TraerDatosTorneoServiceAsync(CapaGUI.ServiceLOC.Torneo torneo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Torneo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long id_Torneo1Field;
        
        private string nombre_Torneo1Field;
        
        private string descripcion_Torneo1Field;
        
        private System.DateTime fecha_Torneo1Field;
        
        private long cantidad_Participante1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id_Torneo1 {
            get {
                return this.id_Torneo1Field;
            }
            set {
                this.id_Torneo1Field = value;
                this.RaisePropertyChanged("Id_Torneo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_Torneo1 {
            get {
                return this.nombre_Torneo1Field;
            }
            set {
                this.nombre_Torneo1Field = value;
                this.RaisePropertyChanged("Nombre_Torneo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion_Torneo1 {
            get {
                return this.descripcion_Torneo1Field;
            }
            set {
                this.descripcion_Torneo1Field = value;
                this.RaisePropertyChanged("Descripcion_Torneo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Fecha_Torneo1 {
            get {
                return this.fecha_Torneo1Field;
            }
            set {
                this.fecha_Torneo1Field = value;
                this.RaisePropertyChanged("Fecha_Torneo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long Cantidad_Participante1 {
            get {
                return this.cantidad_Participante1Field;
            }
            set {
                this.cantidad_Participante1Field = value;
                this.RaisePropertyChanged("Cantidad_Participante1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tipo_Torneo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long id_Tipo_Torneo1Field;
        
        private string nombre_Tipo_torneo1Field;
        
        private string descripcion_Tipo_Torneo1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id_Tipo_Torneo1 {
            get {
                return this.id_Tipo_Torneo1Field;
            }
            set {
                this.id_Tipo_Torneo1Field = value;
                this.RaisePropertyChanged("Id_Tipo_Torneo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_Tipo_torneo1 {
            get {
                return this.nombre_Tipo_torneo1Field;
            }
            set {
                this.nombre_Tipo_torneo1Field = value;
                this.RaisePropertyChanged("Nombre_Tipo_torneo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion_Tipo_Torneo1 {
            get {
                return this.descripcion_Tipo_Torneo1Field;
            }
            set {
                this.descripcion_Tipo_Torneo1Field = value;
                this.RaisePropertyChanged("Descripcion_Tipo_Torneo1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLOCSoapChannel : CapaGUI.ServiceLOC.WebServiceLOCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLOCSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceLOC.WebServiceLOCSoap>, CapaGUI.ServiceLOC.WebServiceLOCSoap {
        
        public WebServiceLOCSoapClient() {
        }
        
        public WebServiceLOCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLOCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLOCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLOCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void agregarTorneoService(CapaGUI.ServiceLOC.Torneo torneo, CapaGUI.ServiceLOC.Tipo_Torneo tp) {
            base.Channel.agregarTorneoService(torneo, tp);
        }
        
        public System.Threading.Tasks.Task agregarTorneoServiceAsync(CapaGUI.ServiceLOC.Torneo torneo, CapaGUI.ServiceLOC.Tipo_Torneo tp) {
            return base.Channel.agregarTorneoServiceAsync(torneo, tp);
        }
        
        public System.Data.DataSet listarTorneoService() {
            return base.Channel.listarTorneoService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listarTorneoServiceAsync() {
            return base.Channel.listarTorneoServiceAsync();
        }
        
        public void modificarTorneoService(CapaGUI.ServiceLOC.Torneo torneo, CapaGUI.ServiceLOC.Tipo_Torneo tp) {
            base.Channel.modificarTorneoService(torneo, tp);
        }
        
        public System.Threading.Tasks.Task modificarTorneoServiceAsync(CapaGUI.ServiceLOC.Torneo torneo, CapaGUI.ServiceLOC.Tipo_Torneo tp) {
            return base.Channel.modificarTorneoServiceAsync(torneo, tp);
        }
        
        public System.Data.DataSet buscarTorneoService(CapaGUI.ServiceLOC.Tipo_Torneo TP) {
            return base.Channel.buscarTorneoService(TP);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscarTorneoServiceAsync(CapaGUI.ServiceLOC.Tipo_Torneo TP) {
            return base.Channel.buscarTorneoServiceAsync(TP);
        }
        
        public void eliminarTorneoService(CapaGUI.ServiceLOC.Torneo torneo) {
            base.Channel.eliminarTorneoService(torneo);
        }
        
        public System.Threading.Tasks.Task eliminarTorneoServiceAsync(CapaGUI.ServiceLOC.Torneo torneo) {
            return base.Channel.eliminarTorneoServiceAsync(torneo);
        }
        
        public System.Data.DataSet buscarIdTorneo() {
            return base.Channel.buscarIdTorneo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscarIdTorneoAsync() {
            return base.Channel.buscarIdTorneoAsync();
        }
        
        public CapaGUI.ServiceLOC.Torneo TraerDatosTorneoService(CapaGUI.ServiceLOC.Torneo torneo) {
            return base.Channel.TraerDatosTorneoService(torneo);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceLOC.Torneo> TraerDatosTorneoServiceAsync(CapaGUI.ServiceLOC.Torneo torneo) {
            return base.Channel.TraerDatosTorneoServiceAsync(torneo);
        }
    }
}
